#!/bin/sh

# PROVIDE: focker_service
# REQUIRE: sshd
# KEYWORD: shutdown

. /etc/rc.subr

name="focker_service"
desc="Focker jails service"
rcvar="focker_service_enable"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

load_rc_config $name

export HOME=/root
export PYTHONPATH=/home/sadaszew/workspace/focker

focker_service_start() {
  /usr/local/bin/python3 <<EOF
from focker.misc import load_jailconf
from focker.core import OSJail
from subprocess import DEVNULL
import sys
conf = load_jailconf()
for name, entry in conf.items():
  import sys
  sys.stdout.write(f'Starting {name} ({entry.get("host.hostname")}) ... ')
  sys.stdout.flush()
  oj = OSJail.from_name(name)
  try:
    oj.start(capture_output=True)
    print('OK')
  except:
    print('Fail')
EOF
}

focker_service_stop() {
  /usr/local/bin/python3 <<EOF
from focker.misc import load_jailconf
from focker.core import OSJail
from subprocess import DEVNULL
import sys
conf = load_jailconf()
for name, entry in conf.items():
  import sys
  oj = OSJail.from_name(name)
  if not oj.is_running:
    continue
  sys.stdout.write(f'Stopping {name} ({entry.get("host.hostname")}) ... ')
  sys.stdout.flush()
  try:
    oj.stop(capture_output=True)
    print('OK')
  except:
    print('Fail')
EOF
}

run_rc_command "$1"
